server {
    listen 8080;
    server_name localhost;

    error_page 400 ./www/errors/400.html;
    error_page 403 ./www/errors/403.html;
    error_page 404 ./www/errors/404.html;
    error_page 405 ./www/errors/405.html;
    error_page 413 ./www/errors/413.html;
    error_page 500 ./www/errors/500.html;

    client_max_body_size 1M;

    location / {
        methods GET;
        root ./www;
        index index.html;
        autoindex off;
    }

    location /upload {
        methods GET;
        root ./www;
        index upload.html;
        autoindex off;
    }

    location /uploads {
        methods GET POST DELETE;
        root ./www/uploads;
        upload_dir ./www/uploads;
        autoindex on;
    }

    location /cgi-bin {
        methods GET POST;
        root ./www/cgi-bin;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    location /old {
        return 301 /;
    }
}
