server {
    listen 8080;
    server_name site1.localhost;

    client_max_body_size 1M;

    location / {
        methods GET;
        root ./www;
        index index.html;
    }
}

server {
    listen 8081;
    server_name site2.localhost;

    client_max_body_size 2M;

    location / {
        methods GET;
        root ./www;
        index index2.html;
    }
}
